const header=document.getElementById('header'), menu=document.getElementById('menu'), nav=document.getElementById('navlinks');
window.addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>20),{passive:true});
menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open)});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(x=>observer.observe(x));
const filters=document.querySelectorAll('.filter'), tiles=document.querySelectorAll('.tile');filters.forEach(btn=>btn.addEventListener('click',()=>{filters.forEach(b=>b.classList.remove('active'));btn.classList.add('active');const f=btn.dataset.filter;tiles.forEach(t=>t.classList.toggle('hide',f!=='all'&&t.dataset.cat!==f))}));
const modal=document.getElementById('modal');tiles.forEach(t=>t.addEventListener('click',()=>{modal.classList.add('open');modal.setAttribute('aria-hidden','false')}));document.getElementById('close').addEventListener('click',()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true')});modal.addEventListener('click',e=>{if(e.target===modal)document.getElementById('close').click()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.classList.contains('open'))document.getElementById('close').click()});
const testimonials=[['“Placeholder testimonial — replace this with a genuine client review that reflects the Fyemsi experience.”','— [Customer Name], [Event Type]'],['“Placeholder testimonial — replace this with an authentic review about the cake, service or event.”','— [Customer Name], [Event Type]'],['“Placeholder testimonial — replace this with a real client story and outcome.”','— [Customer Name], [Event Type]']];let ti=0;setInterval(()=>{ti=(ti+1)%testimonials.length;document.getElementById('testimonial').textContent=testimonials[ti][0];document.getElementById('author').textContent=testimonials[ti][1];document.querySelectorAll('.dot').forEach((d,i)=>d.classList.toggle('active',i===ti))},5000);
const form=document.getElementById('enquiry'),status=document.getElementById('status');form.addEventListener('submit',e=>{e.preventDefault();if(!form.checkValidity()){form.reportValidity();return}const btn=form.querySelector('button[type=submit]');btn.disabled=true;btn.textContent='Sending…';status.classList.remove('show');setTimeout(()=>{status.textContent='Thank you. Your enquiry has been captured in this demo. Connect the form to your email or CRM endpoint to receive submissions.';status.classList.add('show');btn.disabled=false;btn.textContent='Send Enquiry';form.reset()},900)});
